### PR TITLE
Fix Addressbook search error on special character input

### LINKED ISSUE #1103: Interceptor throws when search input contains special characters
Image

### PR DESCRIPTION
**Pull request by jubalm**
Fixes #1103

- [x] remove `.toLowerCase()` transforms in regex match replacing it with `i` flag in `RegExp` constructor

### CODE REVIEW

**Review by KillariDev — COMMENTED** [review]
can we find a function that does the sanitasion for regexp instead of trying to list all cases?

File: app/ts/background/medataSearch.ts [hunk 1]
```diff
@@ -73,8 +73,9 @@ function concatArraysUniqueByAddress<T>(addTo: readonly (T & { address: bigint }
 }
 
 async function filterAddressBookDataByCategoryAndSearchString(addressBookCategory: AddressBookCategory, searchString: string | undefined): Promise<AddressBookEntries> {
+	const unicodeEscapeString = (input: string) => `\\u{${input.charCodeAt(0).toString(16)}}`
```
Comment (KillariDev) [inline app/ts/background/medataSearch.ts:76]:
```suggestion
	const unicodeEscapeString = (input: string) => `\\u{ ${ input.charCodeAt(0).toString(16) } }`
```

**Review by KillariDev — APPROVED** [review]

**Review by KillariDev — APPROVED** [review]
